# Generated by Django 5.0 on 2023-12-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagrm_link',
            new_name='instagram_link',
        ),
    ]
